# <u>Comparisons, Masks, and Boolean Logic</u>

In [1]:
import numpy as np

## Example: Counting Rainy Days

## Comparison Operators as Ufuncs

In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x < 3)
print(x > 3)
print(x <= 3)
print(x >= 3)
print(x != 3)
print(x == 3)

[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [10]:
# It is also possible to do an element-wise comparison of two arrays, and to include compound expressions

(2*x)==(x**2)

array([False,  True, False, False, False])

In [13]:
rag = np.random.default_rng(seed=1701)
x = rag.integers(10, size=(3,4))
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [14]:
x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

## Working with Boolean Arrays

In [15]:
print(x)

[[9 4 0 3]
 [8 6 3 1]
 [3 7 4 0]]


### Counting Entries

In [16]:
# how many values less than 6? 
np.count_nonzero(x < 6)

8

In [17]:
np.sum(x < 6)

8

In [18]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([3, 2, 3])

In [19]:
# are there any values greater than 8?
np.any(x > 8)

True

In [20]:
# are there any values less than zero? 
np.any(x < 0)

False

In [21]:
# are all values less than 10? 
np.all(x < 10)

True

In [22]:
# are all values equal to 6? 
np.all(x == 6)

False

In [23]:
# are all values in each row less than 8? 
np.all(x < 8, axis=1)

array([False, False,  True])

### Boolean Operators

In [28]:
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [25]:
# how many elements are there which are in the interval (3, 8)
np.sum((x > 3) & (x < 8))

4

In [27]:
# how many elements are there which are in the interval (3, 8)
np.sum(~( (x <= 3) | (x >= 8) ))

4

## Boolean Arrays as Masks

In [29]:
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [30]:
# Suppose we want an array of all values in the array that are less than, say, 5

x[x < 5]

array([4, 0, 3, 3, 1, 3, 4, 0])

## Using the Keywords and/or Versus the Operators &/|

In [31]:
bool(42), bool(0)

(True, False)

In [32]:
bool(42 and 0)

False

In [33]:
bool(42 or 0)

True

In [34]:
bin(42)

'0b101010'

In [35]:
bin(59)

'0b111011'

In [36]:
bin(42 & 59)

'0b101010'

In [38]:
bin(42 | 59)

'0b111011'

In [39]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool) 
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool) 
A|B

array([ True,  True,  True, False,  True,  True])

In [41]:
# But if you use or on these arrays it will try to evaluate the truth or falsehood of the entire array object, which is not a well-defined value

A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
# when evaluating a Boolean expression on a given array, you should use | or & rather than or or and

x = np.arange(10) 
(x>4)&(x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [44]:
# Trying to evaluate the truth or falsehood of the entire array will give the same ValueError we saw previously

(x>4)and(x<8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()