# <u>Structured Data: NumPy’s Structured Arrays</u>

In [1]:
import numpy as np

In [2]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [4]:
# We can similarly create a structured array using a compound data type specification

# Use a compound data type for structured arrays

# Here,  
# 'U10' translates to “Unicode string of maximum length 10,” 
# 'i4' translates to “4-byte (i.e., 32-bit) integer,” and 
# 'f8' translates to “8-byte (i.e., 64-bit) float.
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [5]:
data['name'] = name
data['age'] = age
data['weight'] = weight

In [6]:
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
# Get all names 
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row of data 
data[0]

('Alice', 25, 55.)

In [9]:
# Get the name from the last row 
data[-1]['name']

'Doug'

In [10]:
# Get names where age is under 30 
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

## Exploring Structured Array Creation

In [12]:
# numerical types can be specified using Python types or NumPy dtypes instead

np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [13]:
# A compound type can also be specified as a list of tuples

np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [14]:
# If the names of the types do not matter to you, you can specify the types alone in a comma-separated string

np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## More Advanced Compound Types

In [16]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Record Arrays: Structured Arrays with a Twist

In [18]:
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [17]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [19]:
# The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax

%timeit data['age'] 
%timeit data_rec['age']
%timeit data_rec.age

90.6 ns ± 0.0202 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.42 µs ± 5.28 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.15 µs ± 5.17 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
