# <u>The Basics of NumPy Arrays</u>

## NumPy Array Attributes

In [1]:
import numpy as np

In [18]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility

In [19]:
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [20]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ",x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


## Array Indexing: Accessing Single Elements

In [21]:
x1

array([9, 4, 0, 3, 8, 6])

In [22]:
x1[0]

9

In [24]:
x1[-2]

8

In [25]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [28]:
x2[(1, 2)]

2

In [29]:
x2[1, 2]

2

In [31]:
x2[2, -1]

9

In [32]:
x2[0, 0]

3

In [34]:
x2[0, 0] = 12

In [36]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [37]:
x2[0, 0]

12

In [38]:
x1[0] = 3.14159 # this will be truncated!

In [39]:
x1

array([3, 4, 0, 3, 8, 6])

## Array Slicing: Accessing Subarrays

### One-Dimensional Subarrays

In [40]:
x1

array([3, 4, 0, 3, 8, 6])

In [43]:
x1[:3] # first three elements

array([3, 4, 0])

In [44]:
x1[4:] # elements after index 3

array([8, 6])

In [45]:
x1[1:4] # middle subarray

array([4, 0, 3])

In [46]:
x1[::2] # every second element

array([3, 0, 8])

In [47]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

### Multidimensional Subarrays

In [48]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [57]:
x2[:2, :3]         # first two rows & three columns 

array([[12,  1,  3],
       [ 4,  0,  2]])

In [58]:
x2[:3, ::2]        # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [59]:
x2[::-1, ::-1]     # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [65]:
x2[:, 0]           # first column

array([12,  4,  0])

In [64]:
x2[0, :]           # fist row

array([12,  1,  3,  7])

In [66]:
x2[0]

array([12,  1,  3,  7])

### Subarrays as No-Copy Views

In [69]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [70]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  1],
       [ 4,  0]])

In [71]:
# Now if we modify this subarray, we’ll see that the original array is changed

x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 4,  0]])

In [72]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

### Creating Copies of Arrays

In [74]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  1],
       [ 4,  0]])

In [76]:
x2_sub_copy[0,0] = 33
x2_sub_copy

array([[33,  1],
       [ 4,  0]])

In [77]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

### Reshaping of Arrays

In [84]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# A common reshaping operation is converting a one-dimensional array into a two- dimensional row or column matrix:

x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

In [94]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [98]:
# A convenient shorthand for this is to use np.newaxis in the slicing syntax:

x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [99]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

In [3]:
a = np.arange(3)
a.shape

(3,)

In [4]:
a[:, np.newaxis].shape

(3, 1)

In [5]:
a[:, np.newaxis, np.newaxis].shape

(3, 1, 1)

In [7]:
a.shape

(3,)

In [9]:
a[np.newaxis, :].shape

(1, 3)

In [13]:
# That means np.newaxis just adds a '1' to the corresponding side of the shape of the numpy array
# By default it adds one to the left of the shape if ':' is not mentioned
# Also this as well as the reshape() does not mpdify the original array, just gives a different view of the array
a[np.newaxis].shape

(1, 3)

In [12]:
a[np.newaxis, np.newaxis].shape

(1, 1, 3)

## Array Concatenation and Splitting

### Concatenation of Arrays

In [100]:
# np.concatenate takes a tuple or list of arrays as its first argument

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [102]:
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [103]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [104]:
# concatenate along the first axis 
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
# concatenate along the second axis (zero-indexed) 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [106]:
# vertically stack the arrays 
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [107]:
# horizontally stack the arrays 
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [108]:
np.dstack?

Signature: np.dstack(tup)
Docstring:
Stack arrays in sequence depth wise (along third axis).

This is equivalent to concatenation along the third axis after 2-D arrays
of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape
`(N,)` have been reshaped to `(1,N,1)`. Rebuilds arrays divided by
`dsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of arrays
    The arrays must have the same shape along all but the third axis.
    1-D or 2-D arrays must have the same shape.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 3-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays alo

### Splitting of Arrays

In [109]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [113]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print("===============================")
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [117]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
