# <u>Understanding Data Types in Python</u>

### Fixed-Type Arrays in Python

In [2]:
import array
L = list(range(10))
A = array.array('i', L) # Here, 'i' is a type code indicating the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [3]:
import numpy as np

In [4]:
# Integer array 
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
# here, integers are upcast to floating point
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
np.array([3.14, 4, 2, 3], dtype=np.int32)

array([3, 4, 2, 3], dtype=int32)

In [12]:
# Nested lists result in multidimensional arrays
# The inner lists are treated as rows of the resulting two-dimensional array

np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [15]:
# Create a length-10 integer array filled with 0s

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s

np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
 # Create a 3x5 array filled with 3.14

np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# Create a 3x3 array of uniformly distributed pseudorandom values between 0 and 1

np.random.random((3, 5))

array([[0.96411724, 0.7589644 , 0.06456892, 0.36515828, 0.22120458],
       [0.69776963, 0.26879389, 0.72921967, 0.30815214, 0.10133107],
       [0.38491361, 0.7612069 , 0.52169829, 0.2969258 , 0.56564009]])

In [37]:
# Create a 3x3 array of normally distributed pseudorandom values with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[ 0.31090574, -1.10398255,  0.2668496 ],
       [-0.18172794, -0.49218978,  0.94616604],
       [-1.08999447,  0.80491472, -0.31153161]])

In [39]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)

np.random.randint(0, 10, (3,3))

array([[3, 8, 0],
       [7, 3, 4],
       [3, 5, 6]])

In [46]:
# Create a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# Create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location

np.empty(3)

array([0., 0., 0.])

## NumPy Standard Data Types

In [57]:
# when constructing an array, the data type can be specified using a string
np.zeros(10, dtype='int16')

# Or using the associated NumPy object
# using numpy object is better because we can use <TAB> to see the available data types
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)